### ISSUE TITLE
[Question] embedding、reranker image seems to fail when use gpu? 

### ISSUE THREAD

**Issue by cyc00518** [weaviate/reranker-transformers#21]
Hi, guys ,

Can you help check this:
https://forum.weaviate.io/t/question-reranker-image-seems-to-fail-when-use-gpu/4370/3

Quick summary:
1.  semitechnologies's `reranker` images wtih `ENABLE_CUDA=1`  raise `AssertionError: Torch not compiled with CUDA enabled`
2. semitechnologies's `embedding` images wtih `ENABLE_CUDA=1`  don't use gpu.
3. `reranker`  & `embedding` images wtih `ENABLE_CUDA=0` work fine.

**Comment by tdolega** [comment]
Had the same problem. For me solution was those exact lines in container definition:
```
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
 ```
